name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Test with pytest
      run: |
        PYTHONPATH=$PWD pytest tests/ -v --tb=short
    
    - name: Test core emotion arc tool
      run: |
        python tools/chapter_emotion_arc.py samples/sample_chapter.txt --window 5

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -f Dockerfile.mcp -t ffa-lab-9:latest .
    
    - name: Test Docker container
      run: |
        docker run --rm ffa-lab-9:latest python -c "from tools.chapter_emotion_arc import analyze; print('Docker test passed')"